/* ISAAC GAMALIEL SANDOVAL RIVERA                                          */
/* isaac.sandoval@claro.com.gt                                               */

/* CREAR O REMPLAZA LA VISTA */
CREATE OR REPLACE VIEW LOGC_ACCESO.V_LT_VALIDA_TRIM
(CODIGOPAIS, PAISUSUARIO, CODIGO_IP, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, CODIGO_PERFIL_GS, ACCESO,  
CODIGO_USUARIOPERMISO, COD_VAL_EQ_PERF, COD_VAL_PERF_USUA, COD_VAL_RRHH, COD_VAL_VENC, COD_ANALISIS, PORCENTAJE,
DESCRIPCION_PAIS, INICIALES_PAIS, RED, PLATAFORMA, TIPO_SOLICITUD, FAR, COD_EMPLEADO, BAJA, VENCIMIENTO, FECHA_BAJA_RRHH, 
DESCTIPOUSUARIO, USUARIOCONPERMISO, PERFIL_TR, PERFIL_GS, DESCRIPCION_USUARIOPERMISO,
OTRO_PERFIL_GS, VAL_EQ_PERF, VAL_PERF_USUA, VAL_RRHH, VAL_VENC,  ANALISIS,
DESCTIPOSOLICITANTE, DESCEMPRESA, NOMBREGERENCIA, NOMBREAREA, GERENTESOLICITA, BACKOFFICE, SEGURIDAD, ADMINISTRADOR, 
ACTIVIDAD, ESTADO, FECHA_COMPLETADO, PAISENROLADO, ID_GERENCIAENROLADO, GERENCIAENROLADO, ID_AREAENROLADO, 
AREAENROLADO, ID_GERENTEENROLADO, GERENTEENROLADO, TIPOPROCESO, NOMBRETIPOPROCESO, PERMISO, LEADDRESS, 
OTORGADO, FLG_MAR0, ID_MAR, COD_GERENCIA, AREA, FECHA_INGRESO, FECHA_CREACION, FLGSTATUS, CODIGOTIPOSOLICITANTE, 
CODIGOGERENTESOLICITA, CODIGOBACKOFFICE, CODIGOSEGURIDAD, CODIGOADMINISTRADOR, WACWORKFLOWURI, ACTIVO, APROBADO
) AS
/*************/
/*RED FIJA*/
/*************/
SELECT
    X.CODIGOPAIS, X.PAISUSUARIO, X.CODIGO_IP, X.CODIGORED, X.CODIGOPLATAFORMA, TO_CHAR(X.CODIGO_PERFIL_TR) AS CODIGO_PERFIL_TR, 
    TO_CHAR(X.CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS, X.ACCESO, 
    X.CODIGO_USUARIOPERMISO, X.COD_VAL_EQ_PERF, X.COD_VAL_PERF_USUA, X.COD_VAL_RRHH, X.COD_VAL_VENC,
   (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC ) AS COD_ANALISIS,
   ROUND( (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC) / 4 * 100, 0) AS PORCENTAJE, 
    X.DESCRIPCION_PAIS, X.INICIALES_PAIS, X.RED, X.PLATAFORMA, X.TIPO_SOLICITUD, X.FORMULARIO AS FAR, X.USUARIO AS COD_EMPLEADO, X.BAJA, 
    X.VENCIMIENTO, X.FECHA_BAJA_RRHH, X.DESCTIPOUSUARIO, X.USUARIOCONPERMISO, X.PERFIL_TR, X.PERFIL_GS, X.DESCRIPCION_USUARIOPERMISO, 
    CASE WHEN X.COD_VAL_EQ_PERF=0 AND X.COD_VAL_PERF_USUA=0 THEN X.OTRO_PERFIL_GS ELSE NULL END AS OTRO_PERFIL_GS,
    CASE WHEN X.COD_VAL_EQ_PERF=1 THEN 'COINCIDE' ELSE 'NO COINCIDE' END AS VAL_EQ_PERF,
        CASE WHEN X.COD_VAL_PERF_USUA=1 THEN 'EXISTE EN GESTOR' ELSE 'NO EXISTE EN GESTOR' END AS VAL_PERF_USUA,
        CASE WHEN X.COD_VAL_RRHH=1 THEN 'ALTA' ELSE 'BAJA EN CLARO' END AS VAL_RRHH,
        CASE WHEN X.COD_VAL_VENC=1 THEN 'VIGENTE' ELSE 'ACCESO VENCIDO' END AS VAL_VENC,
    CASE WHEN (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC)=4 
      THEN 'CORRECTO' ELSE 'ACCESO INCORRECTO' END AS ANALISIS,
		X.DESCTIPOSOLICITANTE, X.DESCEMPRESA, X.NOMBREGERENCIA, X.NOMBREAREA, X.GERENTESOLICITA, X.BACKOFFICE, X.SEGURIDAD, X.ADMINISTRADOR, 
		X.ACTIVIDAD, X.ESTADO, X.FECHA_COMPLETADO, X.PAISENROLADO, X.ID_GERENCIAENROLADO, X.GERENCIAENROLADO, X.ID_AREAENROLADO, 
		X.AREAENROLADO, X.ID_GERENTEENROLADO, X.GERENTEENROLADO, X.TIPOPROCESO, X.NOMBRETIPOPROCESO, X.PERMISO, X.LEADDRESS, 
		X.OTORGADO, X.FLG_MAR0, X.ID_MAR, X.COD_GERENCIA, X.AREA, X.FECHA_INGRESO, X.FECHA_CREACION, X.FLGSTATUS, X.CODIGOTIPOSOLICITANTE, 
		X.CODIGOGERENTESOLICITA, X.CODIGOBACKOFFICE, X.CODIGOSEGURIDAD, X.CODIGOADMINISTRADOR, X.WACWORKFLOWURI, X.ACTIVO, X.APROBADO      
FROM(    
    SELECT
        A.CODIGOPAIS, A.PAISUSUARIO, B.CODIGO_IP, A.CODIGORED, A.CODIGOPLATAFORMA, A.CODIGOPERFIL AS CODIGO_PERFIL_TR, M.CODIGO_PERFIL AS CODIGO_PERFIL_GS, 
        A.ACCESO, A.FORMULARIO, A.USUARIO, A.CODIGO_USUARIOPERMISO, A.BAJA, A.VENCIMIENTO, I.FECHA_BAJA AS FECHA_BAJA_RRHH, M.DESCRIPCION_PAIS, 
        M.INICIALES_PAIS, A.RED, A.PLATAFORMA, K.TIPO_ACCESO AS TIPO_SOLICITUD, A.PERFIL AS PERFIL_TR, M.DESCRIPCION_PERFIL AS PERFIL_GS, 
        C.DESCRIPCION_USUARIOPERMISO, A.DESCTIPOUSUARIO, A.USUARIOCONPERMISO, L.OTRO_PERFIL_GS,
        CASE 
        WHEN E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
        AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL THEN 1 ELSE 0 END COD_VAL_EQ_PERF,
      	LOGC_ACCESO.FN_CODIGO_PERF_EQ(1, B.CODIGO_IP, A.CODIGOPAIS, E.CODIGO_PERFIL_GS, A.CODIGO_USUARIOPERMISO) AS COD_VAL_PERF_USUA,
        CASE WHEN A.CODIGOTIPOUSUARIO=1 AND I.CODIGO_EMPLEADO=A.USUARIO THEN 0 ELSE 1 END AS COD_VAL_RRHH,
        CASE WHEN A.VENCIMIENTO > SYSDATE THEN 1 ELSE 0 END AS COD_VAL_VENC,
        A.DESCTIPOSOLICITANTE, A.DESCEMPRESA, A.NOMBREGERENCIA, A.NOMBREAREA, A.GERENTESOLICITA, A.BACKOFFICE, A.SEGURIDAD, A.ADMINISTRADOR, 
				A.ACTIVIDAD, A.ESTADO, A.FECHA_COMPLETADO, A.PAISENROLADO, A.ID_GERENCIAENROLADO, A.GERENCIAENROLADO, A.ID_AREAENROLADO, 
				A.AREAENROLADO, A.ID_GERENTEENROLADO, A.GERENTEENROLADO, A.TIPOPROCESO, A.NOMBRETIPOPROCESO, A.PERMISO, A.LEADDRESS, 
				A.OTORGADO, A.FLG_MAR0, A.ID_MAR, A.COD_GERENCIA, A.AREA, A.FECHA_INGRESO, A.FECHA AS FECHA_CREACION, A.FLGSTATUS, A.CODIGOTIPOSOLICITANTE, 
				A.CODIGOGERENTESOLICITA, A.CODIGOBACKOFFICE, A.CODIGOSEGURIDAD, A.CODIGOADMINISTRADOR, A.WACWORKFLOWURI, A.ACTIVO, A.APROBADO
    FROM LOGC_ACCESO.TR_FAR A
    INNER JOIN LOGC_ACCESO.RL_GESTOR_TRIM B
    ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGORED=A.CODIGORED AND B.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND B.TIPO_ACCESO=A.TIPO_SOLICITUD
    INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO C
    ON C.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    LEFT OUTER JOIN(
        SELECT CODIGOPAIS, CODIGO_IP, CODIGORED, CODIGOPLATAFORMA, CODIGOPERFIL AS CODIGO_PERFIL
        FROM LOGC_ACCESO.MT_PERFIL_LOCAL
        WHERE CODIGO_ESTADO_MT='A'
    )D
    ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL
    LEFT OUTER JOIN (
        SELECT
            CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, 
            LISTAGG(CODIGO_PERFIL_GS, ', ') WITHIN GROUP (ORDER BY CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS,
            PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T,
            LISTAGG(PERFIL_G, ' / ') WITHIN GROUP (ORDER BY PERFIL_G) AS PERFIL_G
        FROM LOGC_ACCESO.V_LT_RL_PERFIL_EQUIVALENCIA
        WHERE CODIGO_ESTADO_MT='A'
        GROUP BY CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T
    )E
    ON E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
    AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL
    LEFT OUTER JOIN LOGC_ACCESO.TR_BAR H
    ON H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
    AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO--AND H.BAJA=A.BAJA
    LEFT OUTER JOIN LOGC_ACCESO.TR_RRHH_BAJA I
    ON I.CODIGO_PAIS=A.PAISUSUARIO AND I.CODIGO_EMPLEADO=A.USUARIO
    INNER JOIN (
        SELECT
            CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
            LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
        FROM LOGC_ACCESO.RL_GESTOR_TRIM
        GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
    )K
    ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=B.CODIGO_IP
    LEFT OUTER JOIN (
        /*PERFILES QUE UN USUARIO TIENE ASIGNADOS*/
        SELECT 
        A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO,         
        LISTAGG(D.DESCRIPCION_PERFIL, ' / ') WITHIN GROUP (ORDER BY D.DESCRIPCION_PERFIL) AS OTRO_PERFIL_GS
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_PERFIL_GESTOR_SISTEMA B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL AND B.CODIGO_ESTADO_MT='A'
        INNER JOIN (
            SELECT
                CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
                LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
            FROM LOGC_ACCESO.RL_GESTOR_TRIM
            GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
        )K
        ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=A.CODIGO_IP
        INNER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL D ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=A.CODIGO_IP AND D.CODIGO_PERFIL=A.CODIGO_PERFIL
        INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO E ON E.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
        WHERE A.CODIGO_ESTADO_MT='A'
            AND (CASE WHEN B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL THEN 1 ELSE 0 END)=0
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO
    )L
    ON L.CODIGOPAIS=A.CODIGOPAIS AND L.CODIGO_IP=B.CODIGO_IP AND L.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    INNER JOIN LOG_CONTROL.MT_PAIS M ON M.CODIGO_PAIS=A.CODIGOPAIS
    LEFT OUTER JOIN(
        SELECT 
            A.CODIGOPAIS, A.CODIGO_IP,
            LISTAGG(A.CODIGO_PERFIL, ', ') WITHIN GROUP (ORDER BY A.CODIGO_PERFIL) AS CODIGO_PERFIL,
            LISTAGG(B.DESCRIPCION_PERFIL, ', ') WITHIN GROUP (ORDER BY B.DESCRIPCION_PERFIL) AS DESCRIPCION_PERFIL,
            A.CODIGO_USUARIOPERMISO
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL
        WHERE A.CODIGO_ESTADO_MT='A'
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO    
    )M
    ON M.CODIGOPAIS=A.CODIGOPAIS AND M.CODIGO_IP=B.CODIGO_IP AND M.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO    
    WHERE
    (CASE WHEN D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL THEN 1 ELSE 0 END)=0
    AND (CASE WHEN H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
        AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO AND H.BAJA=A.BAJA 
        AND H.ESTADO='Proceso finalizado' THEN 1 ELSE 0 END)=0
    AND A.CODIGORED=12
)X
/*************/
/*RED MOVIL ERICSSON CENAM*/
/*************/
UNION ALL 
SELECT
    X.CODIGOPAIS, X.PAISUSUARIO, X.CODIGO_IP, X.CODIGORED, X.CODIGOPLATAFORMA, TO_CHAR(X.CODIGO_PERFIL_TR) AS CODIGO_PERFIL_TR, 
    TO_CHAR(X.CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS, X.ACCESO, 
    X.CODIGO_USUARIOPERMISO, X.COD_VAL_EQ_PERF, X.COD_VAL_PERF_USUA, X.COD_VAL_RRHH, X.COD_VAL_VENC, 
   (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC) AS COD_ANALISIS,
   ROUND( (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC) / 4 * 100, 0) AS PORCENTAJE,
    X.DESCRIPCION_PAIS, X.INICIALES_PAIS, X.RED, X.PLATAFORMA, X.TIPO_SOLICITUD, X.FORMULARIO AS FAR, X.USUARIO AS COD_EMPLEADO, X.BAJA, 
    X.VENCIMIENTO, X.FECHA_BAJA_RRHH, X.DESCTIPOUSUARIO, X.USUARIOCONPERMISO, (X.PERFIL_TR || ' ' || X.TIPO_SOLICITUD) AS PERFIL_TR, 
    X.PERFIL_GS, X.DESCRIPCION_USUARIOPERMISO, 
    CASE WHEN X.COD_VAL_EQ_PERF=0 AND X.COD_VAL_PERF_USUA=0 THEN X.OTRO_PERFIL_GS ELSE NULL END AS OTRO_PERFIL_GS,
    CASE WHEN X.COD_VAL_EQ_PERF=1 THEN 'COINCIDE' ELSE 'NO COINCIDE' END AS VAL_EQ_PERF,
        CASE WHEN X.COD_VAL_PERF_USUA=1 THEN 'EXISTE EN GESTOR' ELSE 'NO EXISTE EN GESTOR' END AS VAL_PERF_USUA,
        CASE WHEN X.COD_VAL_RRHH=1 THEN 'ALTA' ELSE 'BAJA EN CLARO' END AS VAL_RRHH,
        CASE WHEN X.COD_VAL_VENC=1 THEN 'VIGENTE' ELSE 'ACCESO VENCIDO' END AS VAL_VENC,
    CASE WHEN (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC)=4 
      THEN 'CORRECTO' ELSE 'ACCESO INCORRECTO' END AS ANALISIS,
		X.DESCTIPOSOLICITANTE, X.DESCEMPRESA, X.NOMBREGERENCIA, X.NOMBREAREA, X.GERENTESOLICITA, X.BACKOFFICE, X.SEGURIDAD, X.ADMINISTRADOR, 
		X.ACTIVIDAD, X.ESTADO, X.FECHA_COMPLETADO, X.PAISENROLADO, X.ID_GERENCIAENROLADO, X.GERENCIAENROLADO, X.ID_AREAENROLADO, 
		X.AREAENROLADO, X.ID_GERENTEENROLADO, X.GERENTEENROLADO, X.TIPOPROCESO, X.NOMBRETIPOPROCESO, X.PERMISO, X.LEADDRESS, 
		X.OTORGADO, X.FLG_MAR0, X.ID_MAR, X.COD_GERENCIA, X.AREA, X.FECHA_INGRESO, X.FECHA_CREACION, X.FLGSTATUS, X.CODIGOTIPOSOLICITANTE, 
		X.CODIGOGERENTESOLICITA, X.CODIGOBACKOFFICE, X.CODIGOSEGURIDAD, X.CODIGOADMINISTRADOR, X.WACWORKFLOWURI, X.ACTIVO, X.APROBADO  
FROM(    
    SELECT
        A.CODIGOPAIS, A.PAISUSUARIO, B.CODIGO_IP, A.CODIGORED, A.CODIGOPLATAFORMA, A.CODIGOPERFIL AS CODIGO_PERFIL_TR, E.CODIGO_PERFIL_GS, 
        A.ACCESO, A.FORMULARIO, A.USUARIO, A.CODIGO_USUARIOPERMISO, A.BAJA, A.VENCIMIENTO, I.FECHA_BAJA AS FECHA_BAJA_RRHH, M.DESCRIPCION_PAIS,
        M.INICIALES_PAIS, A.RED, A.PLATAFORMA, A.TIPO_SOLICITUD, A.PERFIL AS PERFIL_TR, N.DESCRIPCION_PERFIL AS PERFIL_GS,
        C.DESCRIPCION_USUARIOPERMISO, A.DESCTIPOUSUARIO, A.USUARIOCONPERMISO, L.OTRO_PERFIL_GS,
        CASE WHEN E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
        AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL THEN 1 ELSE 0 END COD_VAL_EQ_PERF,
      	LOGC_ACCESO.FN_CODIGO_PERF_EQ(1, B.CODIGO_IP, A.CODIGOPAIS, E.CODIGO_PERFIL_GS, A.CODIGO_USUARIOPERMISO) AS COD_VAL_PERF_USUA,
        CASE WHEN A.CODIGOTIPOUSUARIO=1 AND I.CODIGO_EMPLEADO=A.USUARIO THEN 0 ELSE 1 END AS COD_VAL_RRHH,
        CASE WHEN A.VENCIMIENTO > SYSDATE THEN 1 ELSE 0 END AS COD_VAL_VENC,
        A.DESCTIPOSOLICITANTE, A.DESCEMPRESA, A.NOMBREGERENCIA, A.NOMBREAREA, A.GERENTESOLICITA, A.BACKOFFICE, A.SEGURIDAD, A.ADMINISTRADOR, 
				A.ACTIVIDAD, A.ESTADO, A.FECHA_COMPLETADO, A.PAISENROLADO, A.ID_GERENCIAENROLADO, A.GERENCIAENROLADO, A.ID_AREAENROLADO, 
				A.AREAENROLADO, A.ID_GERENTEENROLADO, A.GERENTEENROLADO, A.TIPOPROCESO, A.NOMBRETIPOPROCESO, A.PERMISO, A.LEADDRESS, 
				A.OTORGADO, A.FLG_MAR0, A.ID_MAR, A.COD_GERENCIA, A.AREA, A.FECHA_INGRESO, A.FECHA AS FECHA_CREACION, A.FLGSTATUS, A.CODIGOTIPOSOLICITANTE, 
				A.CODIGOGERENTESOLICITA, A.CODIGOBACKOFFICE, A.CODIGOSEGURIDAD, A.CODIGOADMINISTRADOR, A.WACWORKFLOWURI, A.ACTIVO, A.APROBADO
    FROM LOGC_ACCESO.TR_FAR A
    INNER JOIN LOGC_ACCESO.RL_GESTOR_TRIM B
    ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGORED=A.CODIGORED AND B.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA
    INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO C
    ON C.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    LEFT OUTER JOIN(
        SELECT CODIGOPAIS, CODIGO_IP, CODIGORED, CODIGOPLATAFORMA, CODIGOPERFIL AS CODIGO_PERFIL
        FROM LOGC_ACCESO.MT_PERFIL_LOCAL
        WHERE CODIGO_ESTADO_MT='A'
    )D
    ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL  
    LEFT OUTER JOIN (
        SELECT
            CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, 
            LISTAGG(CODIGO_PERFIL_GS, ', ') WITHIN GROUP (ORDER BY CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS,
            PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T,
            LISTAGG(PERFIL_G, ' / ') WITHIN GROUP (ORDER BY PERFIL_G) AS PERFIL_G
        FROM LOGC_ACCESO.V_LT_RL_PERFIL_EQUIVALENCIA
        WHERE CODIGO_ESTADO_MT='A'
        GROUP BY CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T    
    ) E
    ON E.CODIGO_IP=B.CODIGO_IP AND E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGORED=A.CODIGORED
    AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL  
    LEFT OUTER JOIN LOGC_ACCESO.TR_BAR H
    ON H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
    AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO--AND H.BAJA=A.BAJA
    LEFT OUTER JOIN LOGC_ACCESO.TR_RRHH_BAJA I
    ON I.CODIGO_PAIS=A.PAISUSUARIO AND I.CODIGO_EMPLEADO=A.USUARIO
    LEFT OUTER JOIN (
        /*PERFILES QUE UN USUARIO TIENE ASIGNADOS*/
        SELECT 
        A.CODIGOPAIS, A.CODIGO_IP, F.DESCRIPCION_CATALOGO AS GROUP_NAME, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO,         
        LISTAGG(D.DESCRIPCION_PERFIL, ' / ') WITHIN GROUP (ORDER BY D.DESCRIPCION_PERFIL) AS OTRO_PERFIL_GS
        FROM LOGM_ERICSSON.RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_PERFIL_GESTOR_SISTEMA B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL AND B.CODIGO_ESTADO_MT='A'
        INNER JOIN (
            SELECT
                CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
                LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
            FROM LOGC_ACCESO.RL_GESTOR_TRIM
            GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
        )K
        ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=A.CODIGO_IP
        INNER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL D ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=A.CODIGO_IP AND D.CODIGO_PERFIL=A.CODIGO_PERFIL
        INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO E ON E.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
        LEFT OUTER JOIN LOGM_ERICSSON.MT_CATALOGO_LOG F
        ON F.CODIGO_TIPO=8 AND F.CODIGO_CATALOGO=A.C_GROUP_NAME        
        WHERE A.CODIGO_ESTADO_MT='A'
            AND (CASE WHEN B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL THEN 1 ELSE 0 END)=0
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, F.DESCRIPCION_CATALOGO, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO
    )L
    ON L.CODIGOPAIS=A.CODIGOPAIS AND L.CODIGO_IP=B.CODIGO_IP AND L.GROUP_NAME=A.TIPO_SOLICITUD AND L.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO    
    INNER JOIN LOG_CONTROL.MT_PAIS M ON M.CODIGO_PAIS=A.CODIGOPAIS
    LEFT OUTER JOIN(
        SELECT 
            A.CODIGOPAIS, A.CODIGO_IP,
            LISTAGG(A.CODIGO_PERFIL, ', ') WITHIN GROUP (ORDER BY A.CODIGO_PERFIL) AS CODIGO_PERFIL,
            LISTAGG(B.DESCRIPCION_PERFIL, ', ') WITHIN GROUP (ORDER BY B.DESCRIPCION_PERFIL) AS DESCRIPCION_PERFIL,
            A.CODIGO_USUARIOPERMISO
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL
        WHERE A.CODIGO_ESTADO_MT='A'
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO    
    )N
    ON N.CODIGOPAIS=A.CODIGOPAIS AND N.CODIGO_IP=B.CODIGO_IP AND N.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO    
    INNER JOIN LOGM_ERICSSON.MT_CATALOGO_LOG X
    ON X.CODIGO_TIPO=8 AND X.DESCRIPCION_CATALOGO=A.TIPO_SOLICITUD  
    WHERE A.CODIGORED=11 AND A.CODIGOPLATAFORMA != 17
    AND A.PERFIL NOT IN ('Administrador', 'Administrator')
)X  
UNION ALL
/*************/
/*RED MOVIL PANAMA*/
/*************/
SELECT
    X.CODIGOPAIS, X.PAISUSUARIO, X.CODIGO_IP, X.CODIGORED, X.CODIGOPLATAFORMA, TO_CHAR(X.CODIGO_PERFIL_TR) AS CODIGO_PERFIL_TR, 
    TO_CHAR(X.CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS, X.ACCESO, 
    X.CODIGO_USUARIOPERMISO, X.COD_VAL_EQ_PERF, X.COD_VAL_PERF_USUA, X.COD_VAL_RRHH, X.COD_VAL_VENC,
   (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC ) AS COD_ANALISIS,
   ROUND( (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC) / 4 * 100, 0) AS PORCENTAJE, 
    X.DESCRIPCION_PAIS, X.INICIALES_PAIS, X.RED, X.PLATAFORMA, X.TIPO_SOLICITUD, X.FORMULARIO AS FAR, X.USUARIO AS COD_EMPLEADO, X.BAJA, 
    X.VENCIMIENTO, X.FECHA_BAJA_RRHH, X.DESCTIPOUSUARIO, X.USUARIOCONPERMISO, X.PERFIL_TR, X.PERFIL_GS, X.DESCRIPCION_USUARIOPERMISO, 
    CASE WHEN X.COD_VAL_EQ_PERF=0 AND X.COD_VAL_PERF_USUA=0 THEN X.OTRO_PERFIL_GS ELSE NULL END AS OTRO_PERFIL_GS,
    CASE WHEN X.COD_VAL_EQ_PERF=1 THEN 'COINCIDE' ELSE 'NO COINCIDE' END AS VAL_EQ_PERF,
        CASE WHEN X.COD_VAL_PERF_USUA=1 THEN 'EXISTE EN GESTOR' ELSE 'NO EXISTE EN GESTOR' END AS VAL_PERF_USUA,
        CASE WHEN X.COD_VAL_RRHH=1 THEN 'ALTA' ELSE 'BAJA EN CLARO' END AS VAL_RRHH,
        CASE WHEN X.COD_VAL_VENC=1 THEN 'VIGENTE' ELSE 'ACCESO VENCIDO' END AS VAL_VENC,
    CASE WHEN (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC)=4 
      THEN 'CORRECTO' ELSE 'ACCESO INCORRECTO' END AS ANALISIS,
        X.DESCTIPOSOLICITANTE, X.DESCEMPRESA, X.NOMBREGERENCIA, X.NOMBREAREA, X.GERENTESOLICITA, X.BACKOFFICE, X.SEGURIDAD, X.ADMINISTRADOR, 
        X.ACTIVIDAD, X.ESTADO, X.FECHA_COMPLETADO, X.PAISENROLADO, X.ID_GERENCIAENROLADO, X.GERENCIAENROLADO, X.ID_AREAENROLADO, 
        X.AREAENROLADO, X.ID_GERENTEENROLADO, X.GERENTEENROLADO, X.TIPOPROCESO, X.NOMBRETIPOPROCESO, X.PERMISO, X.LEADDRESS, 
        X.OTORGADO, X.FLG_MAR0, X.ID_MAR, X.COD_GERENCIA, X.AREA, X.FECHA_INGRESO, X.FECHA_CREACION, X.FLGSTATUS, X.CODIGOTIPOSOLICITANTE, 
        X.CODIGOGERENTESOLICITA, X.CODIGOBACKOFFICE, X.CODIGOSEGURIDAD, X.CODIGOADMINISTRADOR, X.WACWORKFLOWURI, X.ACTIVO, X.APROBADO      
FROM(    
    SELECT
        A.CODIGOPAIS, A.PAISUSUARIO, B.CODIGO_IP, A.CODIGORED, A.CODIGOPLATAFORMA, A.CODIGOPERFIL AS CODIGO_PERFIL_TR, M.CODIGO_PERFIL AS CODIGO_PERFIL_GS, 
        A.ACCESO, A.FORMULARIO, A.USUARIO, A.CODIGO_USUARIOPERMISO, A.BAJA, A.VENCIMIENTO, I.FECHA_BAJA AS FECHA_BAJA_RRHH, M.DESCRIPCION_PAIS, 
        M.INICIALES_PAIS, A.RED, A.PLATAFORMA, K.TIPO_ACCESO AS TIPO_SOLICITUD, A.PERFIL AS PERFIL_TR, M.DESCRIPCION_PERFIL AS PERFIL_GS, 
        C.DESCRIPCION_USUARIOPERMISO, A.DESCTIPOUSUARIO, A.USUARIOCONPERMISO, L.OTRO_PERFIL_GS,
        CASE 
        WHEN E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
        AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL THEN 1 ELSE 0 END COD_VAL_EQ_PERF,
          LOGC_ACCESO.FN_CODIGO_PERF_EQ(1, B.CODIGO_IP, A.CODIGOPAIS, E.CODIGO_PERFIL_GS, A.CODIGO_USUARIOPERMISO) AS COD_VAL_PERF_USUA,
        CASE WHEN A.CODIGOTIPOUSUARIO=1 AND I.CODIGO_EMPLEADO=A.USUARIO THEN 0 ELSE 1 END AS COD_VAL_RRHH,
        CASE WHEN A.VENCIMIENTO > SYSDATE THEN 1 ELSE 0 END AS COD_VAL_VENC,
        A.DESCTIPOSOLICITANTE, A.DESCEMPRESA, A.NOMBREGERENCIA, A.NOMBREAREA, A.GERENTESOLICITA, A.BACKOFFICE, A.SEGURIDAD, A.ADMINISTRADOR, 
                A.ACTIVIDAD, A.ESTADO, A.FECHA_COMPLETADO, A.PAISENROLADO, A.ID_GERENCIAENROLADO, A.GERENCIAENROLADO, A.ID_AREAENROLADO, 
                A.AREAENROLADO, A.ID_GERENTEENROLADO, A.GERENTEENROLADO, A.TIPOPROCESO, A.NOMBRETIPOPROCESO, A.PERMISO, A.LEADDRESS, 
                A.OTORGADO, A.FLG_MAR0, A.ID_MAR, A.COD_GERENCIA, A.AREA, A.FECHA_INGRESO, A.FECHA AS FECHA_CREACION, A.FLGSTATUS, A.CODIGOTIPOSOLICITANTE, 
                A.CODIGOGERENTESOLICITA, A.CODIGOBACKOFFICE, A.CODIGOSEGURIDAD, A.CODIGOADMINISTRADOR, A.WACWORKFLOWURI, A.ACTIVO, A.APROBADO
    FROM LOGC_ACCESO.TR_FAR A
    INNER JOIN LOGC_ACCESO.RL_GESTOR_TRIM B
    ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGORED=A.CODIGORED AND B.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND B.TIPO_ACCESO=A.TIPO_SOLICITUD
    INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO C
    ON C.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    LEFT OUTER JOIN(
        SELECT CODIGOPAIS, CODIGO_IP, CODIGORED, CODIGOPLATAFORMA, CODIGOPERFIL AS CODIGO_PERFIL
        FROM LOGC_ACCESO.MT_PERFIL_LOCAL
        WHERE CODIGO_ESTADO_MT='A'
    )D
    ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL
    LEFT OUTER JOIN (
        SELECT
            CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, 
            LISTAGG(CODIGO_PERFIL_GS, ', ') WITHIN GROUP (ORDER BY CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS,
            PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T,
            LISTAGG(PERFIL_G, ' / ') WITHIN GROUP (ORDER BY PERFIL_G) AS PERFIL_G
        FROM LOGC_ACCESO.V_LT_RL_PERFIL_EQUIVALENCIA
        WHERE CODIGO_ESTADO_MT='A'
        GROUP BY CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T
    )E
    ON E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
    AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL
    LEFT OUTER JOIN LOGC_ACCESO.TR_BAR H
    ON H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
    AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO--AND H.BAJA=A.BAJA
    LEFT OUTER JOIN LOGC_ACCESO.TR_RRHH_BAJA I
    ON I.CODIGO_PAIS=A.PAISUSUARIO AND I.CODIGO_EMPLEADO=A.USUARIO
    INNER JOIN (
        SELECT
            CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
            LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
        FROM LOGC_ACCESO.RL_GESTOR_TRIM
        GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
    )K
    ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=B.CODIGO_IP
    LEFT OUTER JOIN (
        /*PERFILES QUE UN USUARIO TIENE ASIGNADOS*/
        SELECT 
        A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO,         
        LISTAGG(D.DESCRIPCION_PERFIL, ' / ') WITHIN GROUP (ORDER BY D.DESCRIPCION_PERFIL) AS OTRO_PERFIL_GS
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_PERFIL_GESTOR_SISTEMA B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL AND B.CODIGO_ESTADO_MT='A'
        INNER JOIN (
            SELECT
                CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
                LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
            FROM LOGC_ACCESO.RL_GESTOR_TRIM
            GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
        )K
        ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=A.CODIGO_IP
        INNER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL D ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=A.CODIGO_IP AND D.CODIGO_PERFIL=A.CODIGO_PERFIL
        INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO E ON E.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
        WHERE A.CODIGO_ESTADO_MT='A'
            AND (CASE WHEN B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL THEN 1 ELSE 0 END)=0
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO
    )L
    ON L.CODIGOPAIS=A.CODIGOPAIS AND L.CODIGO_IP=B.CODIGO_IP AND L.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    INNER JOIN LOG_CONTROL.MT_PAIS M ON M.CODIGO_PAIS=A.CODIGOPAIS
    LEFT OUTER JOIN(
        SELECT 
            A.CODIGOPAIS, A.CODIGO_IP,
            LISTAGG(A.CODIGO_PERFIL, ', ') WITHIN GROUP (ORDER BY A.CODIGO_PERFIL) AS CODIGO_PERFIL,
            LISTAGG(B.DESCRIPCION_PERFIL, ', ') WITHIN GROUP (ORDER BY B.DESCRIPCION_PERFIL) AS DESCRIPCION_PERFIL,
            A.CODIGO_USUARIOPERMISO
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL
        WHERE A.CODIGO_ESTADO_MT='A'
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO    
    )M
    ON M.CODIGOPAIS=A.CODIGOPAIS AND M.CODIGO_IP=B.CODIGO_IP AND M.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO    
    WHERE
    (CASE WHEN D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL THEN 1 ELSE 0 END)=0
    AND (CASE WHEN H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
        AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO AND H.BAJA=A.BAJA 
        AND H.ESTADO='Proceso finalizado' THEN 1 ELSE 0 END)=0
    AND A.CODIGORED=30 AND A.CODIGOPLATAFORMA=172
)X
/********************
	RED MOVIL SVA
*********************/
UNION ALL
SELECT
    X.CODIGOPAIS, X.PAISUSUARIO, X.CODIGO_IP, X.CODIGORED, X.CODIGOPLATAFORMA, TO_CHAR(X.CODIGO_PERFIL_TR) AS CODIGO_PERFIL_TR, 
    TO_CHAR(X.CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS, X.ACCESO, 
    X.CODIGO_USUARIOPERMISO, X.COD_VAL_EQ_PERF, X.COD_VAL_PERF_USUA, X.COD_VAL_RRHH, X.COD_VAL_VENC,
   (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC ) AS COD_ANALISIS,
   ROUND( (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC) / 4 * 100, 0) AS PORCENTAJE, 
    X.DESCRIPCION_PAIS, X.INICIALES_PAIS, X.RED, X.PLATAFORMA, X.TIPO_SOLICITUD, X.FORMULARIO AS FAR, X.USUARIO AS COD_EMPLEADO, X.BAJA, 
    X.VENCIMIENTO, X.FECHA_BAJA_RRHH, X.DESCTIPOUSUARIO, X.USUARIOCONPERMISO, X.PERFIL_TR, X.PERFIL_GS, X.DESCRIPCION_USUARIOPERMISO, 
    CASE WHEN X.COD_VAL_EQ_PERF=0 AND X.COD_VAL_PERF_USUA=0 THEN X.OTRO_PERFIL_GS ELSE NULL END AS OTRO_PERFIL_GS,
    CASE WHEN X.COD_VAL_EQ_PERF=1 THEN 'COINCIDE' ELSE 'NO COINCIDE' END AS VAL_EQ_PERF,
        CASE WHEN X.COD_VAL_PERF_USUA=1 THEN 'EXISTE EN GESTOR' ELSE 'NO EXISTE EN GESTOR' END AS VAL_PERF_USUA,
        CASE WHEN X.COD_VAL_RRHH=1 THEN 'ALTA' ELSE 'BAJA EN CLARO' END AS VAL_RRHH,
        CASE WHEN X.COD_VAL_VENC=1 THEN 'VIGENTE' ELSE 'ACCESO VENCIDO' END AS VAL_VENC,
    CASE WHEN (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC)=4 
      THEN 'CORRECTO' ELSE 'ACCESO INCORRECTO' END AS ANALISIS,
		X.DESCTIPOSOLICITANTE, X.DESCEMPRESA, X.NOMBREGERENCIA, X.NOMBREAREA, X.GERENTESOLICITA, X.BACKOFFICE, X.SEGURIDAD, X.ADMINISTRADOR, 
		X.ACTIVIDAD, X.ESTADO, X.FECHA_COMPLETADO, X.PAISENROLADO, X.ID_GERENCIAENROLADO, X.GERENCIAENROLADO, X.ID_AREAENROLADO, 
		X.AREAENROLADO, X.ID_GERENTEENROLADO, X.GERENTEENROLADO, X.TIPOPROCESO, X.NOMBRETIPOPROCESO, X.PERMISO, X.LEADDRESS, 
		X.OTORGADO, X.FLG_MAR0, X.ID_MAR, X.COD_GERENCIA, X.AREA, X.FECHA_INGRESO, X.FECHA_CREACION, X.FLGSTATUS, X.CODIGOTIPOSOLICITANTE, 
		X.CODIGOGERENTESOLICITA, X.CODIGOBACKOFFICE, X.CODIGOSEGURIDAD, X.CODIGOADMINISTRADOR, X.WACWORKFLOWURI, X.ACTIVO, X.APROBADO      
FROM(    
    SELECT
        A.CODIGOPAIS, A.PAISUSUARIO, B.CODIGO_IP, A.CODIGORED, A.CODIGOPLATAFORMA, A.CODIGOPERFIL AS CODIGO_PERFIL_TR, M.CODIGO_PERFIL AS CODIGO_PERFIL_GS, 
        A.ACCESO, A.FORMULARIO, A.USUARIO, A.CODIGO_USUARIOPERMISO, A.BAJA, A.VENCIMIENTO, I.FECHA_BAJA AS FECHA_BAJA_RRHH, M.DESCRIPCION_PAIS, 
        M.INICIALES_PAIS, A.RED, A.PLATAFORMA, K.TIPO_ACCESO AS TIPO_SOLICITUD, A.PERFIL AS PERFIL_TR, M.DESCRIPCION_PERFIL AS PERFIL_GS, 
        C.DESCRIPCION_USUARIOPERMISO, A.DESCTIPOUSUARIO, A.USUARIOCONPERMISO, L.OTRO_PERFIL_GS,
        CASE 
        WHEN E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
        AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL THEN 1 ELSE 0 END COD_VAL_EQ_PERF,
      	LOGC_ACCESO.FN_CODIGO_PERF_EQ(1, B.CODIGO_IP, A.CODIGOPAIS, E.CODIGO_PERFIL_GS, A.CODIGO_USUARIOPERMISO) AS COD_VAL_PERF_USUA,
        CASE WHEN A.CODIGOTIPOUSUARIO=1 AND I.CODIGO_EMPLEADO=A.USUARIO THEN 0 ELSE 1 END AS COD_VAL_RRHH,
        CASE WHEN A.VENCIMIENTO > SYSDATE THEN 1 ELSE 0 END AS COD_VAL_VENC,
        A.DESCTIPOSOLICITANTE, A.DESCEMPRESA, A.NOMBREGERENCIA, A.NOMBREAREA, A.GERENTESOLICITA, A.BACKOFFICE, A.SEGURIDAD, A.ADMINISTRADOR, 
				A.ACTIVIDAD, A.ESTADO, A.FECHA_COMPLETADO, A.PAISENROLADO, A.ID_GERENCIAENROLADO, A.GERENCIAENROLADO, A.ID_AREAENROLADO, 
				A.AREAENROLADO, A.ID_GERENTEENROLADO, A.GERENTEENROLADO, A.TIPOPROCESO, A.NOMBRETIPOPROCESO, A.PERMISO, A.LEADDRESS, 
				A.OTORGADO, A.FLG_MAR0, A.ID_MAR, A.COD_GERENCIA, A.AREA, A.FECHA_INGRESO, A.FECHA AS FECHA_CREACION, A.FLGSTATUS, A.CODIGOTIPOSOLICITANTE, 
				A.CODIGOGERENTESOLICITA, A.CODIGOBACKOFFICE, A.CODIGOSEGURIDAD, A.CODIGOADMINISTRADOR, A.WACWORKFLOWURI, A.ACTIVO, A.APROBADO
    FROM LOGC_ACCESO.TR_FAR A
    INNER JOIN LOGC_ACCESO.RL_GESTOR_TRIM B
    ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGORED=A.CODIGORED AND B.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND B.TIPO_ACCESO=A.PLATAFORMA
    INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO C
    ON C.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    LEFT OUTER JOIN(
        SELECT CODIGOPAIS, CODIGO_IP, CODIGORED, CODIGOPLATAFORMA, CODIGOPERFIL AS CODIGO_PERFIL
        FROM LOGC_ACCESO.MT_PERFIL_LOCAL
        WHERE CODIGO_ESTADO_MT='A'
    )D
    ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL
    LEFT OUTER JOIN (
        SELECT
            CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, 
            LISTAGG(CODIGO_PERFIL_GS, ', ') WITHIN GROUP (ORDER BY CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS,
            PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T,
            LISTAGG(PERFIL_G, ' / ') WITHIN GROUP (ORDER BY PERFIL_G) AS PERFIL_G
        FROM LOGC_ACCESO.V_LT_RL_PERFIL_EQUIVALENCIA
        WHERE CODIGO_ESTADO_MT='A'
        GROUP BY CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T
    )E
    ON E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
    AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL
    LEFT OUTER JOIN LOGC_ACCESO.TR_BAR H
    ON H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
    AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO--AND H.BAJA=A.BAJA
    LEFT OUTER JOIN LOGC_ACCESO.TR_RRHH_BAJA I
    ON I.CODIGO_PAIS=A.PAISUSUARIO AND I.CODIGO_EMPLEADO=A.USUARIO
    INNER JOIN (
        SELECT
            CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
            LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
        FROM LOGC_ACCESO.RL_GESTOR_TRIM
        GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
    )K
    ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=B.CODIGO_IP
    LEFT OUTER JOIN (
        /*PERFILES QUE UN USUARIO TIENE ASIGNADOS*/
        SELECT 
        A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO,         
        LISTAGG(D.DESCRIPCION_PERFIL, ' / ') WITHIN GROUP (ORDER BY D.DESCRIPCION_PERFIL) AS OTRO_PERFIL_GS
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_PERFIL_GESTOR_SISTEMA B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL AND B.CODIGO_ESTADO_MT='A'
        INNER JOIN (
            SELECT
                CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
                LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
            FROM LOGC_ACCESO.RL_GESTOR_TRIM
            GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
        )K
        ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=A.CODIGO_IP
        INNER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL D ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=A.CODIGO_IP AND D.CODIGO_PERFIL=A.CODIGO_PERFIL
        INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO E ON E.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
        WHERE A.CODIGO_ESTADO_MT='A'
            AND (CASE WHEN B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL THEN 1 ELSE 0 END)=0
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO
    )L
    ON L.CODIGOPAIS=A.CODIGOPAIS AND L.CODIGO_IP=B.CODIGO_IP AND L.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    INNER JOIN LOG_CONTROL.MT_PAIS M ON M.CODIGO_PAIS=A.CODIGOPAIS
    LEFT OUTER JOIN(
        SELECT 
            A.CODIGOPAIS, A.CODIGO_IP,
            LISTAGG(A.CODIGO_PERFIL, ', ') WITHIN GROUP (ORDER BY A.CODIGO_PERFIL) AS CODIGO_PERFIL,
            LISTAGG(B.DESCRIPCION_PERFIL, ', ') WITHIN GROUP (ORDER BY B.DESCRIPCION_PERFIL) AS DESCRIPCION_PERFIL,
            A.CODIGO_USUARIOPERMISO
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL
        WHERE A.CODIGO_ESTADO_MT='A'
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO    
    )M
    ON M.CODIGOPAIS=A.CODIGOPAIS AND M.CODIGO_IP=B.CODIGO_IP AND M.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO    
    WHERE
    (CASE WHEN D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL THEN 1 ELSE 0 END)=0
    AND (CASE WHEN H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
        AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO AND H.BAJA=A.BAJA 
        AND H.ESTADO='Proceso finalizado' THEN 1 ELSE 0 END)=0
    AND A.CODIGORED=14
)X
/*************/
/*SERVIDOR SEGURO*/
/*************/
UNION ALL
SELECT
    X.CODIGOPAIS, X.PAISUSUARIO, X.CODIGO_IP, X.CODIGORED, X.CODIGOPLATAFORMA, TO_CHAR(X.CODIGO_PERFIL_TR) AS CODIGO_PERFIL_TR, 
    TO_CHAR(X.CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS, X.ACCESO, 
    X.CODIGO_USUARIOPERMISO, X.COD_VAL_EQ_PERF, X.COD_VAL_PERF_USUA, X.COD_VAL_RRHH, X.COD_VAL_VENC,
   (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC ) AS COD_ANALISIS,
   ROUND( (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC) / 4 * 100, 0) AS PORCENTAJE, 
    X.DESCRIPCION_PAIS, X.INICIALES_PAIS, X.RED, X.PLATAFORMA, X.TIPO_SOLICITUD, X.FORMULARIO AS FAR, X.USUARIO AS COD_EMPLEADO, X.BAJA, 
    X.VENCIMIENTO, X.FECHA_BAJA_RRHH, X.DESCTIPOUSUARIO, X.USUARIOCONPERMISO, X.PERFIL_TR, X.PERFIL_GS, X.DESCRIPCION_USUARIOPERMISO, 
    CASE WHEN X.COD_VAL_EQ_PERF=0 AND X.COD_VAL_PERF_USUA=0 THEN X.OTRO_PERFIL_GS ELSE NULL END AS OTRO_PERFIL_GS,
    CASE WHEN X.COD_VAL_EQ_PERF=1 THEN 'COINCIDE' ELSE 'NO COINCIDE' END AS VAL_EQ_PERF,
        CASE WHEN X.COD_VAL_PERF_USUA=1 THEN 'EXISTE EN GESTOR' ELSE 'NO EXISTE EN GESTOR' END AS VAL_PERF_USUA,
        CASE WHEN X.COD_VAL_RRHH=1 THEN 'ALTA' ELSE 'BAJA EN CLARO' END AS VAL_RRHH,
        CASE WHEN X.COD_VAL_VENC=1 THEN 'VIGENTE' ELSE 'ACCESO VENCIDO' END AS VAL_VENC,
    CASE WHEN (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC)=4 
      THEN 'CORRECTO' ELSE 'ACCESO INCORRECTO' END AS ANALISIS,
		X.DESCTIPOSOLICITANTE, X.DESCEMPRESA, X.NOMBREGERENCIA, X.NOMBREAREA, X.GERENTESOLICITA, X.BACKOFFICE, X.SEGURIDAD, X.ADMINISTRADOR, 
		X.ACTIVIDAD, X.ESTADO, X.FECHA_COMPLETADO, X.PAISENROLADO, X.ID_GERENCIAENROLADO, X.GERENCIAENROLADO, X.ID_AREAENROLADO, 
		X.AREAENROLADO, X.ID_GERENTEENROLADO, X.GERENTEENROLADO, X.TIPOPROCESO, X.NOMBRETIPOPROCESO, X.PERMISO, X.LEADDRESS, 
		X.OTORGADO, X.FLG_MAR0, X.ID_MAR, X.COD_GERENCIA, X.AREA, X.FECHA_INGRESO, X.FECHA_CREACION, X.FLGSTATUS, X.CODIGOTIPOSOLICITANTE, 
		X.CODIGOGERENTESOLICITA, X.CODIGOBACKOFFICE, X.CODIGOSEGURIDAD, X.CODIGOADMINISTRADOR, X.WACWORKFLOWURI, X.ACTIVO, X.APROBADO      
FROM(    
    SELECT
        A.CODIGOPAIS, A.PAISUSUARIO, B.CODIGO_IP, A.CODIGORED, A.CODIGOPLATAFORMA, A.CODIGOPERFIL AS CODIGO_PERFIL_TR, M.CODIGO_PERFIL AS CODIGO_PERFIL_GS, 
        A.ACCESO, A.FORMULARIO, A.USUARIO, A.CODIGO_USUARIOPERMISO, A.BAJA, A.VENCIMIENTO, I.FECHA_BAJA AS FECHA_BAJA_RRHH, M.DESCRIPCION_PAIS, 
        M.INICIALES_PAIS, A.RED, A.PLATAFORMA, K.TIPO_ACCESO AS TIPO_SOLICITUD, A.PERFIL AS PERFIL_TR, M.DESCRIPCION_PERFIL AS PERFIL_GS, 
        C.DESCRIPCION_USUARIOPERMISO, A.DESCTIPOUSUARIO, A.USUARIOCONPERMISO, L.OTRO_PERFIL_GS,
        CASE 
        WHEN E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
        AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL THEN 1 ELSE 0 END COD_VAL_EQ_PERF,
      	LOGC_ACCESO.FN_CODIGO_PERF_EQ(1, B.CODIGO_IP, A.CODIGOPAIS, E.CODIGO_PERFIL_GS, A.CODIGO_USUARIOPERMISO) AS COD_VAL_PERF_USUA,
        CASE WHEN A.CODIGOTIPOUSUARIO=1 AND I.CODIGO_EMPLEADO=A.USUARIO THEN 0 ELSE 1 END AS COD_VAL_RRHH,
        CASE WHEN A.VENCIMIENTO > SYSDATE THEN 1 ELSE 0 END AS COD_VAL_VENC,
        A.DESCTIPOSOLICITANTE, A.DESCEMPRESA, A.NOMBREGERENCIA, A.NOMBREAREA, A.GERENTESOLICITA, A.BACKOFFICE, A.SEGURIDAD, A.ADMINISTRADOR, 
				A.ACTIVIDAD, A.ESTADO, A.FECHA_COMPLETADO, A.PAISENROLADO, A.ID_GERENCIAENROLADO, A.GERENCIAENROLADO, A.ID_AREAENROLADO, 
				A.AREAENROLADO, A.ID_GERENTEENROLADO, A.GERENTEENROLADO, A.TIPOPROCESO, A.NOMBRETIPOPROCESO, A.PERMISO, A.LEADDRESS, 
				A.OTORGADO, A.FLG_MAR0, A.ID_MAR, A.COD_GERENCIA, A.AREA, A.FECHA_INGRESO, A.FECHA AS FECHA_CREACION, A.FLGSTATUS, A.CODIGOTIPOSOLICITANTE, 
				A.CODIGOGERENTESOLICITA, A.CODIGOBACKOFFICE, A.CODIGOSEGURIDAD, A.CODIGOADMINISTRADOR, A.WACWORKFLOWURI, A.ACTIVO, A.APROBADO
    FROM LOGC_ACCESO.TR_FAR A
    INNER JOIN LOGC_ACCESO.RL_GESTOR_TRIM B
    ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGORED=A.CODIGORED AND B.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND B.TIPO_ACCESO=A.TIPO_SOLICITUD
    INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO C
    ON C.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    LEFT OUTER JOIN(
        SELECT CODIGOPAIS, CODIGO_IP, CODIGORED, CODIGOPLATAFORMA, CODIGOPERFIL AS CODIGO_PERFIL
        FROM LOGC_ACCESO.MT_PERFIL_LOCAL
        WHERE CODIGO_ESTADO_MT='A'
    )D
    ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL
    LEFT OUTER JOIN (
        SELECT
            CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, 
            LISTAGG(CODIGO_PERFIL_GS, ', ') WITHIN GROUP (ORDER BY CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS,
            PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T,
            LISTAGG(PERFIL_G, ' / ') WITHIN GROUP (ORDER BY PERFIL_G) AS PERFIL_G
        FROM LOGC_ACCESO.V_LT_RL_PERFIL_EQUIVALENCIA
        WHERE CODIGO_ESTADO_MT='A'
        GROUP BY CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T
    )E
    ON E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
    AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL
    LEFT OUTER JOIN LOGC_ACCESO.TR_BAR H
    ON H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
    AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO--AND H.BAJA=A.BAJA
    LEFT OUTER JOIN LOGC_ACCESO.TR_RRHH_BAJA I
    ON I.CODIGO_PAIS=A.PAISUSUARIO AND I.CODIGO_EMPLEADO=A.USUARIO
    INNER JOIN (
        SELECT
            CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
            LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
        FROM LOGC_ACCESO.RL_GESTOR_TRIM
        GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
    )K
    ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=B.CODIGO_IP
    LEFT OUTER JOIN (
        /*PERFILES QUE UN USUARIO TIENE ASIGNADOS*/
        SELECT 
        A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO,         
        LISTAGG(D.DESCRIPCION_PERFIL, ' / ') WITHIN GROUP (ORDER BY D.DESCRIPCION_PERFIL) AS OTRO_PERFIL_GS
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_PERFIL_GESTOR_SISTEMA B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL AND B.CODIGO_ESTADO_MT='A'
        INNER JOIN (
            SELECT
                CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
                LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
            FROM LOGC_ACCESO.RL_GESTOR_TRIM
            GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
        )K
        ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=A.CODIGO_IP
        INNER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL D ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=A.CODIGO_IP AND D.CODIGO_PERFIL=A.CODIGO_PERFIL
        INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO E ON E.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
        WHERE A.CODIGO_ESTADO_MT='A'
            AND (CASE WHEN B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL THEN 1 ELSE 0 END)=0
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO
    )L
    ON L.CODIGOPAIS=A.CODIGOPAIS AND L.CODIGO_IP=B.CODIGO_IP AND L.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    INNER JOIN LOG_CONTROL.MT_PAIS M ON M.CODIGO_PAIS=A.CODIGOPAIS
    LEFT OUTER JOIN(
        SELECT 
            A.CODIGOPAIS, A.CODIGO_IP,
            LISTAGG(A.CODIGO_PERFIL, ', ') WITHIN GROUP (ORDER BY A.CODIGO_PERFIL) AS CODIGO_PERFIL,
            LISTAGG(B.DESCRIPCION_PERFIL, ', ') WITHIN GROUP (ORDER BY B.DESCRIPCION_PERFIL) AS DESCRIPCION_PERFIL,
            A.CODIGO_USUARIOPERMISO
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL
        WHERE A.CODIGO_ESTADO_MT='A'
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO    
    )M
    ON M.CODIGOPAIS=A.CODIGOPAIS AND M.CODIGO_IP=B.CODIGO_IP AND M.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO    
    WHERE
    (CASE WHEN D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL THEN 1 ELSE 0 END)=0
    AND (CASE WHEN H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
        AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO AND H.BAJA=A.BAJA 
        AND H.ESTADO='Proceso finalizado' THEN 1 ELSE 0 END)=0
    AND A.CODIGORED=34
)X
/**************************   
RED SVA RBT
**************************/
UNION ALL
SELECT
    X.CODIGOPAIS, X.PAISUSUARIO, X.CODIGO_IP, X.CODIGORED, X.CODIGOPLATAFORMA, TO_CHAR(X.CODIGO_PERFIL_TR) AS CODIGO_PERFIL_TR, 
    TO_CHAR(X.CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS, X.ACCESO, 
    X.CODIGO_USUARIOPERMISO, X.COD_VAL_EQ_PERF, X.COD_VAL_PERF_USUA, X.COD_VAL_RRHH, X.COD_VAL_VENC,
   (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC ) AS COD_ANALISIS,
   ROUND( (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC) / 4 * 100, 0) AS PORCENTAJE, 
    X.DESCRIPCION_PAIS, X.INICIALES_PAIS, X.RED, X.PLATAFORMA, X.TIPO_SOLICITUD, X.FORMULARIO AS FAR, X.USUARIO AS COD_EMPLEADO, X.BAJA, 
    X.VENCIMIENTO, X.FECHA_BAJA_RRHH, X.DESCTIPOUSUARIO, X.USUARIOCONPERMISO, X.PERFIL_TR, X.PERFIL_GS, X.DESCRIPCION_USUARIOPERMISO, 
    CASE WHEN X.COD_VAL_EQ_PERF=0 AND X.COD_VAL_PERF_USUA=0 THEN X.OTRO_PERFIL_GS ELSE NULL END AS OTRO_PERFIL_GS,
    CASE WHEN X.COD_VAL_EQ_PERF=1 THEN 'COINCIDE' ELSE 'NO COINCIDE' END AS VAL_EQ_PERF,
        CASE WHEN X.COD_VAL_PERF_USUA=1 THEN 'EXISTE EN GESTOR' ELSE 'NO EXISTE EN GESTOR' END AS VAL_PERF_USUA,
        CASE WHEN X.COD_VAL_RRHH=1 THEN 'ALTA' ELSE 'BAJA EN CLARO' END AS VAL_RRHH,
        CASE WHEN X.COD_VAL_VENC=1 THEN 'VIGENTE' ELSE 'ACCESO VENCIDO' END AS VAL_VENC,
    CASE WHEN (X.COD_VAL_EQ_PERF + X.COD_VAL_PERF_USUA + X.COD_VAL_RRHH + X.COD_VAL_VENC)=4 
      THEN 'CORRECTO' ELSE 'ACCESO INCORRECTO' END AS ANALISIS,
		X.DESCTIPOSOLICITANTE, X.DESCEMPRESA, X.NOMBREGERENCIA, X.NOMBREAREA, X.GERENTESOLICITA, X.BACKOFFICE, X.SEGURIDAD, X.ADMINISTRADOR, 
		X.ACTIVIDAD, X.ESTADO, X.FECHA_COMPLETADO, X.PAISENROLADO, X.ID_GERENCIAENROLADO, X.GERENCIAENROLADO, X.ID_AREAENROLADO, 
		X.AREAENROLADO, X.ID_GERENTEENROLADO, X.GERENTEENROLADO, X.TIPOPROCESO, X.NOMBRETIPOPROCESO, X.PERMISO, X.LEADDRESS, 
		X.OTORGADO, X.FLG_MAR0, X.ID_MAR, X.COD_GERENCIA, X.AREA, X.FECHA_INGRESO, X.FECHA_CREACION, X.FLGSTATUS, X.CODIGOTIPOSOLICITANTE, 
		X.CODIGOGERENTESOLICITA, X.CODIGOBACKOFFICE, X.CODIGOSEGURIDAD, X.CODIGOADMINISTRADOR, X.WACWORKFLOWURI, X.ACTIVO, X.APROBADO      
FROM(    
    SELECT
        A.CODIGOPAIS, A.PAISUSUARIO, B.CODIGO_IP, A.CODIGORED, A.CODIGOPLATAFORMA, A.CODIGOPERFIL AS CODIGO_PERFIL_TR, M.CODIGO_PERFIL AS CODIGO_PERFIL_GS, 
        A.ACCESO, A.FORMULARIO, A.USUARIO, A.CODIGO_USUARIOPERMISO, A.BAJA, A.VENCIMIENTO, I.FECHA_BAJA AS FECHA_BAJA_RRHH, M.DESCRIPCION_PAIS, 
        M.INICIALES_PAIS, A.RED, A.PLATAFORMA, K.TIPO_ACCESO AS TIPO_SOLICITUD, A.PERFIL AS PERFIL_TR, M.DESCRIPCION_PERFIL AS PERFIL_GS, 
        C.DESCRIPCION_USUARIOPERMISO, A.DESCTIPOUSUARIO, A.USUARIOCONPERMISO, L.OTRO_PERFIL_GS,
        CASE 
        WHEN E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
        AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL THEN 1 ELSE 0 END COD_VAL_EQ_PERF,
      	LOGC_ACCESO.FN_CODIGO_PERF_EQ(1, B.CODIGO_IP, A.CODIGOPAIS, E.CODIGO_PERFIL_GS, A.CODIGO_USUARIOPERMISO) AS COD_VAL_PERF_USUA,
        CASE WHEN A.CODIGOTIPOUSUARIO=1 AND I.CODIGO_EMPLEADO=A.USUARIO THEN 0 ELSE 1 END AS COD_VAL_RRHH,
        CASE WHEN A.VENCIMIENTO > SYSDATE THEN 1 ELSE 0 END AS COD_VAL_VENC,
        A.DESCTIPOSOLICITANTE, A.DESCEMPRESA, A.NOMBREGERENCIA, A.NOMBREAREA, A.GERENTESOLICITA, A.BACKOFFICE, A.SEGURIDAD, A.ADMINISTRADOR, 
				A.ACTIVIDAD, A.ESTADO, A.FECHA_COMPLETADO, A.PAISENROLADO, A.ID_GERENCIAENROLADO, A.GERENCIAENROLADO, A.ID_AREAENROLADO, 
				A.AREAENROLADO, A.ID_GERENTEENROLADO, A.GERENTEENROLADO, A.TIPOPROCESO, A.NOMBRETIPOPROCESO, A.PERMISO, A.LEADDRESS, 
				A.OTORGADO, A.FLG_MAR0, A.ID_MAR, A.COD_GERENCIA, A.AREA, A.FECHA_INGRESO, A.FECHA AS FECHA_CREACION, A.FLGSTATUS, A.CODIGOTIPOSOLICITANTE, 
				A.CODIGOGERENTESOLICITA, A.CODIGOBACKOFFICE, A.CODIGOSEGURIDAD, A.CODIGOADMINISTRADOR, A.WACWORKFLOWURI, A.ACTIVO, A.APROBADO
    FROM LOGC_ACCESO.TR_FAR A
    INNER JOIN LOGC_ACCESO.RL_GESTOR_TRIM B
    ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGORED=A.CODIGORED AND B.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND B.TIPO_ACCESO=A.TIPO_SOLICITUD
    INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO C
    ON C.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    LEFT OUTER JOIN(
        SELECT CODIGOPAIS, CODIGO_IP, CODIGORED, CODIGOPLATAFORMA, CODIGOPERFIL AS CODIGO_PERFIL
        FROM LOGC_ACCESO.MT_PERFIL_LOCAL
        WHERE CODIGO_ESTADO_MT='A'
    )D
    ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL
    LEFT OUTER JOIN (
        SELECT
            CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, 
            LISTAGG(CODIGO_PERFIL_GS, ', ') WITHIN GROUP (ORDER BY CODIGO_PERFIL_GS) AS CODIGO_PERFIL_GS,
            PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T,
            LISTAGG(PERFIL_G, ' / ') WITHIN GROUP (ORDER BY PERFIL_G) AS PERFIL_G
        FROM LOGC_ACCESO.V_LT_RL_PERFIL_EQUIVALENCIA
        WHERE CODIGO_ESTADO_MT='A'
        GROUP BY CODIGO_IP, CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_PERFIL_TR, PAIS_B, RED_B, PLATAFORMA_B, PERFIL_T
    )E
    ON E.CODIGOPAIS=A.CODIGOPAIS AND E.CODIGO_IP=B.CODIGO_IP AND E.CODIGORED=A.CODIGORED
    AND E.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND E.CODIGO_PERFIL_TR=A.CODIGOPERFIL
    LEFT OUTER JOIN LOGC_ACCESO.TR_BAR H
    ON H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
    AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO--AND H.BAJA=A.BAJA
    LEFT OUTER JOIN LOGC_ACCESO.TR_RRHH_BAJA I
    ON I.CODIGO_PAIS=A.PAISUSUARIO AND I.CODIGO_EMPLEADO=A.USUARIO
    INNER JOIN (
        SELECT
            CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
            LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
        FROM LOGC_ACCESO.RL_GESTOR_TRIM
        GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
    )K
    ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=B.CODIGO_IP
    LEFT OUTER JOIN (
        /*PERFILES QUE UN USUARIO TIENE ASIGNADOS*/
        SELECT 
        A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO,         
        LISTAGG(D.DESCRIPCION_PERFIL, ' / ') WITHIN GROUP (ORDER BY D.DESCRIPCION_PERFIL) AS OTRO_PERFIL_GS
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_PERFIL_GESTOR_SISTEMA B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL AND B.CODIGO_ESTADO_MT='A'
        INNER JOIN (
            SELECT
                CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP, 
                LISTAGG(TIPO_ACCESO, ' / ') WITHIN GROUP (ORDER BY TIPO_ACCESO) AS TIPO_ACCESO
            FROM LOGC_ACCESO.RL_GESTOR_TRIM
            GROUP BY CODIGOPAIS, CODIGORED, CODIGOPLATAFORMA, CODIGO_IP
        )K
        ON K.CODIGOPAIS=A.CODIGOPAIS AND K.CODIGO_IP=A.CODIGO_IP
        INNER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL D ON D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=A.CODIGO_IP AND D.CODIGO_PERFIL=A.CODIGO_PERFIL
        INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO E ON E.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
        WHERE A.CODIGO_ESTADO_MT='A'
            AND (CASE WHEN B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL THEN 1 ELSE 0 END)=0
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO, E.DESCRIPCION_USUARIOPERMISO
    )L
    ON L.CODIGOPAIS=A.CODIGOPAIS AND L.CODIGO_IP=B.CODIGO_IP AND L.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO
    INNER JOIN LOG_CONTROL.MT_PAIS M ON M.CODIGO_PAIS=A.CODIGOPAIS
    LEFT OUTER JOIN(
        SELECT 
            A.CODIGOPAIS, A.CODIGO_IP,
            LISTAGG(A.CODIGO_PERFIL, ', ') WITHIN GROUP (ORDER BY A.CODIGO_PERFIL) AS CODIGO_PERFIL,
            LISTAGG(B.DESCRIPCION_PERFIL, ', ') WITHIN GROUP (ORDER BY B.DESCRIPCION_PERFIL) AS DESCRIPCION_PERFIL,
            A.CODIGO_USUARIOPERMISO
        FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
        LEFT OUTER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL B
        ON B.CODIGOPAIS=A.CODIGOPAIS AND B.CODIGO_IP=A.CODIGO_IP AND B.CODIGO_PERFIL=A.CODIGO_PERFIL
        WHERE A.CODIGO_ESTADO_MT='A'
        GROUP BY A.CODIGOPAIS, A.CODIGO_IP, A.CODIGO_USUARIOPERMISO    
    )M
    ON M.CODIGOPAIS=A.CODIGOPAIS AND M.CODIGO_IP=B.CODIGO_IP AND M.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO    
    WHERE
    (CASE WHEN D.CODIGOPAIS=A.CODIGOPAIS AND D.CODIGO_IP=B.CODIGO_IP AND D.CODIGORED=A.CODIGORED
    AND D.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND D.CODIGO_PERFIL=A.CODIGOPERFIL THEN 1 ELSE 0 END)=0
    AND (CASE WHEN H.CODIGOPAIS=A.CODIGOPAIS AND H.CODIGORED=A.CODIGORED AND H.CODIGOPLATAFORMA=A.CODIGOPLATAFORMA AND H.CODIGOPERFIL=A.CODIGOPERFIL 
        AND H.ACCESO=A.ACCESO AND H.FORMULARIO=A.FORMULARIO AND H.USUARIO=A.USUARIO AND H.CODIGO_USUARIOPERMISO=A.CODIGO_USUARIOPERMISO AND H.BAJA=A.BAJA 
        AND H.ESTADO='Proceso finalizado' THEN 1 ELSE 0 END)=0
    AND A.CODIGORED=14
)X
/********************
	RED MOVIL ATAE
*********************/
UNION ALL
SELECT X.CODIGOPAIS,
          X.PAISUSUARIO,
          X.CODIGO_IP,
          X.CODIGORED,
          X.CODIGOPLATAFORMA,
          TO_CHAR (X.CODIGO_PERFIL_TR)
             AS CODIGO_PERFIL_TR,
          TO_CHAR (X.CODIGO_PERFIL_GS)
             AS CODIGO_PERFIL_GS,
          X.ACCESO,
          X.CODIGO_USUARIOPERMISO,
          X.COD_VAL_EQ_PERF,
          X.COD_VAL_PERF_USUA,
          X.COD_VAL_RRHH,
          X.COD_VAL_VENC,
          (  X.COD_VAL_EQ_PERF
           + X.COD_VAL_PERF_USUA
           + X.COD_VAL_RRHH
           + X.COD_VAL_VENC)
             AS COD_ANALISIS,
          ROUND (
               (  X.COD_VAL_EQ_PERF
                + X.COD_VAL_PERF_USUA
                + X.COD_VAL_RRHH
                + X.COD_VAL_VENC)
             / 4
             * 100,
             0)
             AS PORCENTAJE,
          X.DESCRIPCION_PAIS,
          X.INICIALES_PAIS,
          X.RED,
          X.PLATAFORMA,
          X.TIPO_SOLICITUD,
          X.FORMULARIO
             AS FAR,
          X.USUARIO
             AS COD_EMPLEADO,
          X.BAJA,
          X.VENCIMIENTO,
          X.FECHA_BAJA_RRHH,
          X.DESCTIPOUSUARIO,
          X.USUARIOCONPERMISO,
          X.PERFIL_TR,
          X.PERFIL_GS,
          X.DESCRIPCION_USUARIOPERMISO,
          CASE
             WHEN X.COD_VAL_EQ_PERF = 0 AND X.COD_VAL_PERF_USUA = 0
             THEN
                X.OTRO_PERFIL_GS
             ELSE
                NULL
          END
             AS OTRO_PERFIL_GS,
          CASE
             WHEN X.COD_VAL_EQ_PERF = 1 THEN 'COINCIDE'
             ELSE 'NO COINCIDE'
          END
             AS VAL_EQ_PERF,
          CASE
             WHEN X.COD_VAL_PERF_USUA = 1 THEN 'EXISTE EN GESTOR'
             ELSE 'NO EXISTE EN GESTOR'
          END
             AS VAL_PERF_USUA,
          CASE WHEN X.COD_VAL_RRHH = 1 THEN 'ALTA' ELSE 'BAJA EN CLARO' END
             AS VAL_RRHH,
          CASE
             WHEN X.COD_VAL_VENC = 1 THEN 'VIGENTE'
             ELSE 'ACCESO VENCIDO'
          END
             AS VAL_VENC,
          CASE
             WHEN (  X.COD_VAL_EQ_PERF
                   + X.COD_VAL_PERF_USUA
                   + X.COD_VAL_RRHH
                   + X.COD_VAL_VENC) =
                  4
             THEN
                'CORRECTO'
             ELSE
                'ACCESO INCORRECTO'
          END
             AS ANALISIS,
          X.DESCTIPOSOLICITANTE,
          X.DESCEMPRESA,
          X.NOMBREGERENCIA,
          X.NOMBREAREA,
          X.GERENTESOLICITA,
          X.BACKOFFICE,
          X.SEGURIDAD,
          X.ADMINISTRADOR,
          X.ACTIVIDAD,
          X.ESTADO,
          X.FECHA_COMPLETADO,
          X.PAISENROLADO,
          X.ID_GERENCIAENROLADO,
          X.GERENCIAENROLADO,
          X.ID_AREAENROLADO,
          X.AREAENROLADO,
          X.ID_GERENTEENROLADO,
          X.GERENTEENROLADO,
          X.TIPOPROCESO,
          X.NOMBRETIPOPROCESO,
          X.PERMISO,
          X.LEADDRESS,
          X.OTORGADO,
          X.FLG_MAR0,
          X.ID_MAR,
          X.COD_GERENCIA,
          X.AREA,
          X.FECHA_INGRESO,
          X.FECHA_CREACION,
          X.FLGSTATUS,
          X.CODIGOTIPOSOLICITANTE,
          X.CODIGOGERENTESOLICITA,
          X.CODIGOBACKOFFICE,
          X.CODIGOSEGURIDAD,
          X.CODIGOADMINISTRADOR,
          X.WACWORKFLOWURI,
          X.ACTIVO,
          X.APROBADO
     FROM (SELECT A.CODIGOPAIS,
                  A.PAISUSUARIO,
                  B.CODIGO_IP,
                  A.CODIGORED,
                  A.CODIGOPLATAFORMA,
                  A.CODIGOPERFIL
                     AS CODIGO_PERFIL_TR,
                  M.CODIGO_PERFIL
                     AS CODIGO_PERFIL_GS,
                  A.ACCESO,
                  A.FORMULARIO,
                  A.USUARIO,
                  A.CODIGO_USUARIOPERMISO,
                  A.BAJA,
                  A.VENCIMIENTO,
                  I.FECHA_BAJA
                     AS FECHA_BAJA_RRHH,
                  M.DESCRIPCION_PAIS,
                  M.INICIALES_PAIS,
                  A.RED,
                  A.PLATAFORMA,
                  K.TIPO_ACCESO
                     AS TIPO_SOLICITUD,
                  A.PERFIL
                     AS PERFIL_TR,
                  M.DESCRIPCION_PERFIL
                     AS PERFIL_GS,
                  C.DESCRIPCION_USUARIOPERMISO,
                  A.DESCTIPOUSUARIO,
                  A.USUARIOCONPERMISO,
                  L.OTRO_PERFIL_GS,
                  CASE
                     WHEN     E.CODIGOPAIS = A.CODIGOPAIS
                          AND E.CODIGO_IP = B.CODIGO_IP
                          AND E.CODIGORED = A.CODIGORED
                          AND E.CODIGOPLATAFORMA = A.CODIGOPLATAFORMA
                          AND E.CODIGO_PERFIL_TR = A.CODIGOPERFIL
                     THEN
                        1
                     ELSE
                        0
                  END
                     COD_VAL_EQ_PERF,
                  LOGC_ACCESO.FN_CODIGO_PERF_EQ (1,
                                                 B.CODIGO_IP,
                                                 A.CODIGOPAIS,
                                                 E.CODIGO_PERFIL_GS,
                                                 A.CODIGO_USUARIOPERMISO)
                     AS COD_VAL_PERF_USUA,
                  CASE
                     WHEN     A.CODIGOTIPOUSUARIO = 1
                          AND I.CODIGO_EMPLEADO = A.USUARIO
                     THEN
                        0
                     ELSE
                        1
                  END
                     AS COD_VAL_RRHH,
                  CASE WHEN A.VENCIMIENTO > SYSDATE THEN 1 ELSE 0 END
                     AS COD_VAL_VENC,
                  A.DESCTIPOSOLICITANTE,
                  A.DESCEMPRESA,
                  A.NOMBREGERENCIA,
                  A.NOMBREAREA,
                  A.GERENTESOLICITA,
                  A.BACKOFFICE,
                  A.SEGURIDAD,
                  A.ADMINISTRADOR,
                  A.ACTIVIDAD,
                  A.ESTADO,
                  A.FECHA_COMPLETADO,
                  A.PAISENROLADO,
                  A.ID_GERENCIAENROLADO,
                  A.GERENCIAENROLADO,
                  A.ID_AREAENROLADO,
                  A.AREAENROLADO,
                  A.ID_GERENTEENROLADO,
                  A.GERENTEENROLADO,
                  A.TIPOPROCESO,
                  A.NOMBRETIPOPROCESO,
                  A.PERMISO,
                  A.LEADDRESS,
                  A.OTORGADO,
                  A.FLG_MAR0,
                  A.ID_MAR,
                  A.COD_GERENCIA,
                  A.AREA,
                  A.FECHA_INGRESO,
                  A.FECHA
                     AS FECHA_CREACION,
                  A.FLGSTATUS,
                  A.CODIGOTIPOSOLICITANTE,
                  A.CODIGOGERENTESOLICITA,
                  A.CODIGOBACKOFFICE,
                  A.CODIGOSEGURIDAD,
                  A.CODIGOADMINISTRADOR,
                  A.WACWORKFLOWURI,
                  A.ACTIVO,
                  A.APROBADO
             FROM LOGC_ACCESO.TR_FAR  A
                  INNER JOIN LOGC_ACCESO.RL_GESTOR_TRIM B
                     ON     B.CODIGOPAIS = A.CODIGOPAIS
                        AND B.CODIGORED = A.CODIGORED
                        AND B.CODIGOPLATAFORMA = A.CODIGOPLATAFORMA
                        AND B.TIPO_ACCESO = A.TIPO_SOLICITUD
                  INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO C
                     ON C.CODIGO_USUARIOPERMISO = A.CODIGO_USUARIOPERMISO
                  LEFT OUTER JOIN (SELECT CODIGOPAIS,
                                          CODIGO_IP,
                                          CODIGORED,
                                          CODIGOPLATAFORMA,
                                          CODIGOPERFIL    AS CODIGO_PERFIL
                                     FROM LOGC_ACCESO.MT_PERFIL_LOCAL
                                    WHERE CODIGO_ESTADO_MT = 'A') D
                     ON     D.CODIGOPAIS = A.CODIGOPAIS
                        AND D.CODIGO_IP = B.CODIGO_IP
                        AND D.CODIGORED = A.CODIGORED
                        AND D.CODIGOPLATAFORMA = A.CODIGOPLATAFORMA
                        AND D.CODIGO_PERFIL = A.CODIGOPERFIL
                  LEFT OUTER JOIN
                  (  SELECT CODIGO_IP,
                            CODIGOPAIS,
                            CODIGORED,
                            CODIGOPLATAFORMA,
                            CODIGO_PERFIL_TR,
                            LISTAGG (CODIGO_PERFIL_GS, ', ')
                               WITHIN GROUP (ORDER BY CODIGO_PERFIL_GS)
                               AS CODIGO_PERFIL_GS,
                            PAIS_B,
                            RED_B,
                            PLATAFORMA_B,
                            PERFIL_T,
                            LISTAGG (PERFIL_G, ' / ')
                               WITHIN GROUP (ORDER BY PERFIL_G)
                               AS PERFIL_G
                       FROM LOGC_ACCESO.V_LT_RL_PERFIL_EQUIVALENCIA
                      WHERE CODIGO_ESTADO_MT = 'A'
                   GROUP BY CODIGO_IP,
                            CODIGOPAIS,
                            CODIGORED,
                            CODIGOPLATAFORMA,
                            CODIGO_PERFIL_TR,
                            PAIS_B,
                            RED_B,
                            PLATAFORMA_B,
                            PERFIL_T) E
                     ON     E.CODIGOPAIS = A.CODIGOPAIS
                        AND E.CODIGO_IP = B.CODIGO_IP
                        AND E.CODIGORED = A.CODIGORED
                        AND E.CODIGOPLATAFORMA = A.CODIGOPLATAFORMA
                        AND E.CODIGO_PERFIL_TR = A.CODIGOPERFIL
                  LEFT OUTER JOIN LOGC_ACCESO.TR_BAR H
                     ON     H.CODIGOPAIS = A.CODIGOPAIS
                        AND H.CODIGORED = A.CODIGORED
                        AND H.CODIGOPLATAFORMA = A.CODIGOPLATAFORMA
                        AND H.CODIGOPERFIL = A.CODIGOPERFIL
                        AND H.ACCESO = A.ACCESO
                        AND H.FORMULARIO = A.FORMULARIO
                        AND H.USUARIO = A.USUARIO
                        AND H.CODIGO_USUARIOPERMISO = A.CODIGO_USUARIOPERMISO --AND H.BAJA=A.BAJA
                  LEFT OUTER JOIN LOGC_ACCESO.TR_RRHH_BAJA I
                     ON     I.CODIGO_PAIS = A.PAISUSUARIO
                        AND I.CODIGO_EMPLEADO = A.USUARIO
                  INNER JOIN
                  (  SELECT CODIGOPAIS,
                            CODIGORED,
                            CODIGOPLATAFORMA,
                            CODIGO_IP,
                            LISTAGG (TIPO_ACCESO, ' / ')
                               WITHIN GROUP (ORDER BY TIPO_ACCESO)
                               AS TIPO_ACCESO
                       FROM LOGC_ACCESO.RL_GESTOR_TRIM
                   GROUP BY CODIGOPAIS,
                            CODIGORED,
                            CODIGOPLATAFORMA,
                            CODIGO_IP) K
                     ON     K.CODIGOPAIS = A.CODIGOPAIS
                        AND K.CODIGO_IP = B.CODIGO_IP
                  LEFT OUTER JOIN
                  (  /*PERFILES QUE UN USUARIO TIENE ASIGNADOS*/
                     SELECT A.CODIGOPAIS,
                            A.CODIGO_IP,
                            A.CODIGO_USUARIOPERMISO,
                            E.DESCRIPCION_USUARIOPERMISO,
                            LISTAGG (D.DESCRIPCION_PERFIL, ' / ')
                               WITHIN GROUP (ORDER BY D.DESCRIPCION_PERFIL)
                               AS OTRO_PERFIL_GS
                       FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
                            LEFT OUTER JOIN
                            LOGC_ACCESO.TR_PERFIL_GESTOR_SISTEMA B
                               ON     B.CODIGOPAIS = A.CODIGOPAIS
                                  AND B.CODIGO_IP = A.CODIGO_IP
                                  AND B.CODIGO_PERFIL = A.CODIGO_PERFIL
                                  AND B.CODIGO_ESTADO_MT = 'A'
                            INNER JOIN
                            (  SELECT CODIGOPAIS,
                                      CODIGORED,
                                      CODIGOPLATAFORMA,
                                      CODIGO_IP,
                                      LISTAGG (TIPO_ACCESO, ' / ')
                                         WITHIN GROUP (ORDER BY TIPO_ACCESO)
                                         AS TIPO_ACCESO
                                 FROM LOGC_ACCESO.RL_GESTOR_TRIM
                             GROUP BY CODIGOPAIS,
                                      CODIGORED,
                                      CODIGOPLATAFORMA,
                                      CODIGO_IP) K
                               ON     K.CODIGOPAIS = A.CODIGOPAIS
                                  AND K.CODIGO_IP = A.CODIGO_IP
                            INNER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL D
                               ON     D.CODIGOPAIS = A.CODIGOPAIS
                                  AND D.CODIGO_IP = A.CODIGO_IP
                                  AND D.CODIGO_PERFIL = A.CODIGO_PERFIL
                            INNER JOIN LOG_CONTROL.MT_USUARIOPERMISO E
                               ON E.CODIGO_USUARIOPERMISO =
                                  A.CODIGO_USUARIOPERMISO
                      WHERE     A.CODIGO_ESTADO_MT = 'A'
                            AND (CASE
                                    WHEN     B.CODIGOPAIS = A.CODIGOPAIS
                                         AND B.CODIGO_IP = A.CODIGO_IP
                                         AND B.CODIGO_PERFIL = A.CODIGO_PERFIL
                                    THEN
                                       1
                                    ELSE
                                       0
                                 END) =
                                0
                   GROUP BY A.CODIGOPAIS,
                            A.CODIGO_IP,
                            A.CODIGO_USUARIOPERMISO,
                            E.DESCRIPCION_USUARIOPERMISO) L
                     ON     L.CODIGOPAIS = A.CODIGOPAIS
                        AND L.CODIGO_IP = B.CODIGO_IP
                        AND L.CODIGO_USUARIOPERMISO = A.CODIGO_USUARIOPERMISO
                  INNER JOIN LOG_CONTROL.MT_PAIS M
                     ON M.CODIGO_PAIS = A.CODIGOPAIS
                  LEFT OUTER JOIN
                  (  SELECT A.CODIGOPAIS,
                            A.CODIGO_IP,
                            LISTAGG (A.CODIGO_PERFIL, ', ')
                               WITHIN GROUP (ORDER BY A.CODIGO_PERFIL)
                               AS CODIGO_PERFIL,
                            LISTAGG (B.DESCRIPCION_PERFIL, ', ')
                               WITHIN GROUP (ORDER BY B.DESCRIPCION_PERFIL)
                               AS DESCRIPCION_PERFIL,
                            A.CODIGO_USUARIOPERMISO
                       FROM LOGC_ACCESO.V_LT_RL_ROLE_USER A
                            LEFT OUTER JOIN LOGC_ACCESO.TR_GESTOR_PERFIL B
                               ON     B.CODIGOPAIS = A.CODIGOPAIS
                                  AND B.CODIGO_IP = A.CODIGO_IP
                                  AND B.CODIGO_PERFIL = A.CODIGO_PERFIL
                      WHERE A.CODIGO_ESTADO_MT = 'A'
                   GROUP BY A.CODIGOPAIS,
                            A.CODIGO_IP,
                            A.CODIGO_USUARIOPERMISO) M
                     ON     M.CODIGOPAIS = A.CODIGOPAIS
                        AND M.CODIGO_IP = B.CODIGO_IP
                        AND M.CODIGO_USUARIOPERMISO = A.CODIGO_USUARIOPERMISO
            WHERE     (CASE
                          WHEN     D.CODIGOPAIS = A.CODIGOPAIS
                               AND D.CODIGO_IP = B.CODIGO_IP
                               AND D.CODIGORED = A.CODIGORED
                               AND D.CODIGOPLATAFORMA = A.CODIGOPLATAFORMA
                               AND D.CODIGO_PERFIL = A.CODIGOPERFIL
                          THEN
                             1
                          ELSE
                             0
                       END) =
                      0
                  AND (CASE
                          WHEN     H.CODIGOPAIS = A.CODIGOPAIS
                               AND H.CODIGORED = A.CODIGORED
                               AND H.CODIGOPLATAFORMA = A.CODIGOPLATAFORMA
                               AND H.CODIGOPERFIL = A.CODIGOPERFIL
                               AND H.ACCESO = A.ACCESO
                               AND H.FORMULARIO = A.FORMULARIO
                               AND H.USUARIO = A.USUARIO
                               AND H.CODIGO_USUARIOPERMISO =
                                   A.CODIGO_USUARIOPERMISO
                               AND H.BAJA = A.BAJA
                               AND H.ESTADO = 'Proceso finalizado'
                          THEN
                             1
                          ELSE
                             0
                       END) =
                      0
                  ) X WHERE X.CODIGORED = 11
                  AND X.CODIGOPLATAFORMA = 17;
